name = 'Имя'
subname = 'Фамилия'
birth = 'Дата рождения'
format_date = 'дд.мм.гггг'
all_ = 'Все'
gender = 'Пол'
male = 'Мужчина'
female = 'Женщина'
photo = 'Основная фотография'
phone = 'Контактный телефон или родителей'
e_mail = 'Почта'
skype = 'Skype (опционально)'
facebook = 'Facebook (опционально)'
height_cm = 'Рост см.'
weight_kg = 'Вес кг.'
model_s = 'Параметры модели (опционально)'
model_s_plc = '90-60-90'
shoe_s = 'Размер обуви'
model_exp = 'Модельный опыт'
add = 'Дополнительная информация (опционально)'
add_place = 'Татуировки, родимые пятна, дифекты кожи'
button_submit = 'Отправить форму'
submit = 'Отправить'

message_required = 'Обязательно для заполнения'
message_email = 'Неверный email'
message_email_exist = 'Модель с таким адресом существует'
message_phone = 'Неверно введен номер телефона'
message_phone_exist = 'Модель с таким номером существует'
message_image_format = 'Только изображения с расширением ".jpg"'
message_model_size_input_error = 'Неверно введеные параметры (90-60-90)'
message_already_exist = 'Такая модель существует в базе!'

min_value = 'от'
max_value = 'до'

message_re_first_name = 'Некорректное имя'
message_re_last_name = 'Некорректная фамилия'